loginpage/urls.py
from django.contrib import admin
from django.urls import path

from .views import loginView, registerView

app_name = 'loginpage'

urlpatterns = [
    path('login/', loginView, name="loginView"),
    path('register/', registerView, name="registerView"),
    # path('logout/', logoutUser, name="logoutUser"),
]

story9xx/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import index

urlpatterns = [
    path('', index),
    path('admin/', admin.site.urls),
    path('user/', include('loginpage.urls'), name="loginpage"),
]

loginpage/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=0)

    def save(self):
        super().save()

    def __str__(self):
        return self.user.username

loginpage/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1']

    error_messages = {
        'required' : 'Please Type',
        'unique': 'About user with this username already exists.',
        'password_mismatch' : "Password and confirm password don't match",
    }

    username_attrs = {
        'placeholder' : 'Username',
        'class' : 'form-control',
        'required' : True,
        'unique' : True,
    }

    password_attrs = {
        'placeholder' : 'Password',
        'class' : 'form-control',
        'required' : True,
    }

    username = forms.SlugField(label="Username",widget=forms.TextInput(attrs=username_attrs))
    password1 = forms.CharField(label="Password",widget=forms.PasswordInput(attrs=password_attrs))
    password2 = forms.CharField(label="Password",widget=forms.PasswordInput(attrs=password_attrs))
    

loginpage/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import MyUserCreationForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login , logout
from .models import Profile
from django.contrib.auth.models import User

# Create your views here.

def loginView(request):
    context = {
        'page_title':'LOGIN',
    }
    user = None

    if request.method == "GET":
        if request.user.is_authenticated:
            # logika untuk user
            return redirect("/")
        else:
            # logika untuk anonymous
            return render(request, 'login.html', context)


    if request.method == "POST":
        
        username_login = request.POST['username']
        password_login = request.POST['password']
        
        user = authenticate(request, username=username_login, password=password_login)

        if user is not None:
            login(request, user)
            return redirect("/")
        else:
            return redirect("/user/login/")

    return render(request, 'login.html', context)


response={}
def registerView(request):
    form = MyUserCreationForm(request.POST)
    if request.method=='POST':
        print(form.errors)
        if form.is_valid():
            userz = form.save()
            name = form.cleaned_data.get("username")
            passw = form.cleaned_data.get("password1")
            user = authenticate(username=name, password=passw)
            instance = Profile(user=userz)
            instance.save()
            messages.success(request, "User with name " + name +" is built successfully")
            return redirect ("/user/register/")
        else:
            messages.warning(request, form.errors)
    form = MyUserCreationForm()
    response['form'] = form
    return render(request, 'register.html', response)


@login_required
def logoutUser(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            logout(request)

            return redirect("/")

story9xx/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    return render(request, 'homepage.html')

loginpage/templates/login.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="container-fluid">
    
    <div class="row">
        <br><br><br><br><br>
    </div>
    
    <div class="row">
        <p id="welcome" class="mx-auto">Welcome !!<p>
    </div>
    
    <div class="row">
        <br><br><br><br><br>
    </div>

    <div class="row">
        <div class="card mx-sm-auto">
            <div class="card-body">
                <h2>Sign In</h2>
                <br> 	                      
                <form method="POST">
                    {% csrf_token %}
                    <input class="col-12" type="text" id="username" name="username" placeholder="Username">
                    <br><br>
                    <input class="col-12" type="password" id="password" name="password" placeholder="Password">
                    <br><br>
                    <button class="float-right" type="submit">Login</button>
                </form>
                <br><br><br><br>
                <p class="d-flex justify-content-center">Don't have an account? &nbsp;<a href="{% url 'loginpage:registerView' %}">Sign Up</a></p>                               
            </div>
        </div>        
    </div>

    <div class="row">
        <br>
    </div>

</div>

{% endblock content %}

loginpage/templates/register.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="container-fluid">
    
    <div class="row">
        <br><br><br><br><br>
    </div>
    
    <div class="row">
        <p id="welcome" class="mx-auto">Welcome !!<p>
    </div>
    
    <div class="row">
        <br><br><br><br><br>
    </div>

    <div class="row">
        <div class="card mx-sm-auto">
            <div class="card-body">
                <h2>Register</h2>
                <br> 	                      
                <form action="/user/register/" method="POST" class="col-12">
                    {% csrf_token %}
                    {{ form.username }}
                    <br>
                    {{ form.password1 }}
                    <br>
                    {{ form.password2 }}
                    <br><br>
                    <button class="float-right" type="submit" method="POST">Sign Up</button> 
                </form>                 
                <br><br><br><br>
                <p class="d-flex justify-content-center">Already have an account? &nbsp;<a href="{% url 'loginpage:loginView' %}">Login</a></p>                
            </div>
        </div>        
    </div>

    <div class="row">
        <br>
    </div>

</div>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome !!</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/story9.css' %}">
</head>
<body>
    {% block content %}
    {% endblock content %}
</body>
</html>

templates/homepage.html
{% extends 'base.html' %}

{% load static %}


{% block content %}
<div class="container-fluid">
    
    <div class="row">
        <br><br><br><br>
    </div>
    
    <div class="row">
        <br><br><br><br>
    </div>
    
    <div class="row">
        <p id="welcome" class="mx-auto">Welcome !! {{user}}<p>
    </div>

    <div class="row">
        <br><br>
    </div>

    <div class="row">
        <div class="col-md">
            
        </div>
        <div class="col-md d-flex justify-content-center">
            <a href="{% url 'loginpage:registerView' %}"><button>Register</button></a>&nbsp;&nbsp;&nbsp;
            <a href="{% url 'loginpage:loginView' %}"><button>Login</button></a>
        </div>
        <div class="col-md">
            
        </div>
        
    </div>

    <div class="row">
        <br><br>
    </div>

</div>
{% endblock content %}